name: Build LEDE Firmware

on:
  workflow_dispatch:  # 允许手动触发工作流
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  LEDE_REPO: https://github.com/coolsnowwolf/lede
  FEEDS_CONF: feeds.conf.default

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180  # 编译可能需要较长时间

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone LEDE source
      run: |
        git clone $LEDE_REPO lede
        cd lede
        git checkout master

    - name: Add device definition
      run: |
        # 创建设备定义文件
        cat > lede/target/linux/rockchip/image/hugsun_ax3000.mk << 'EOF'
        define Device/hugsun_ax3000
          DEVICE_VENDOR := Hugsun
          SOC := rk3528
          UBOOT_DEVICE_NAME := generic-rk3528
          IMAGE/sysupgrade.img.gz := boot-common | boot-script rk3528 | pine64-img | gzip | append-metadata
          DEVICE_MODEL := Hugsun AX3000
          DEVICE_PACKAGES := kmod-mt7915e kmod-mt7915-firmware kmod-usb3 kmod-usb-ledtrig-usbport
        endef
        TARGET_DEVICES += hugsun_ax3000
        EOF

    - name: Setup build environment
      run: |
        cd lede
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib \
          g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils \
          rsync unzip zlib1g-dev file wget

    - name: Update feeds
      run: |
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure target
      run: |
        cd lede
        # 设置目标为rockchip和rk35xx
        cat > .config << 'EOF'
        CONFIG_TARGET_rockchip=y
        CONFIG_TARGET_rockchip_rk35xx=y
        CONFIG_TARGET_rockchip_rk35xx_DEVICE_hugsun_ax3000=y
        CONFIG_ALL_KMODS=y
        CONFIG_IB=y
        CONFIG_IMAGEOPT=y
        CONFIG_KDIR_TARBALL=y
        EOF

    - name: Run menuconfig (optional)
      run: |
        cd lede
        make defconfig
        # 取消注释下一行以交互式配置（需要虚拟帧缓冲区）
        # make menuconfig

    - name: Build firmware
      run: |
        cd lede
        make -j$(nproc) V=s

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hugsun-ax3000-firmware
        path: |
          lede/bin/targets/rockchip/rk35xx/*.gz
          lede/bin/targets/rockchip/rk35xx/*.img
        if-no-files-found: error
        retention-days: 7
